#!/usr/bin/env python3
"""
Simple Python HTTP server for YouTube caption extraction
Run this with: python caption-server.py
Then access test page at: http://localhost:8000/test-captions.html
"""

from http.server import HTTPServer, BaseHTTPRequestHandler
from youtube_transcript_api import YouTubeTranscriptApi
import json
import os

class CaptionHandler(BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()

    def do_POST(self):
        if self.path == '/api/youtube-captions':
            try:
                # Read request body
                content_length = int(self.headers['Content-Length'])
                post_data = self.rfile.read(content_length)
                body = json.loads(post_data.decode('utf-8'))

                video_id = body.get('videoId')

                if not video_id:
                    self.send_json_response(400, {'error': 'Missing videoId'})
                    return

                print(f'Fetching captions for video: {video_id}', flush=True)

                # Fetch transcript using correct API (static methods)
                # First, get list of available transcripts
                try:
                    print(f'Getting list of available transcripts...', flush=True)
                    transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

                    # Try to find English transcript first (any English variant)
                    try:
                        print(f'Attempting to fetch English captions...', flush=True)
                        # Try multiple English variants: en, en-US, en-GB, etc.
                        transcript = transcript_list.find_transcript(['en', 'en-US', 'en-GB', 'en-CA', 'en-AU'])
                        fetched_transcript = transcript.fetch()
                        print(f'Successfully fetched English captions ({transcript.language})!', flush=True)
                    except:
                        # If English not available, get the first available transcript
                        print(f'English not available, fetching first available language...', flush=True)
                        # Get first manually created or auto-generated transcript
                        try:
                            # Try to get any manually created transcript
                            transcript = next(iter(transcript_list))
                            fetched_transcript = transcript.fetch()
                            print(f'Successfully fetched captions in {transcript.language}!', flush=True)
                        except:
                            # Last resort: try to get any transcript at all
                            all_transcripts = list(transcript_list)
                            if all_transcripts:
                                transcript = all_transcripts[0]
                                fetched_transcript = transcript.fetch()
                                print(f'Successfully fetched captions in {transcript.language}!', flush=True)
                            else:
                                fetched_transcript = None

                except Exception as e:
                    print(f'No transcripts available: {type(e).__name__}: {str(e)}', flush=True)
                    fetched_transcript = None

                if not fetched_transcript:
                    self.send_json_response(404, {
                        'error': 'No captions available',
                        'hasCaptions': False
                    })
                    return

                # The fetch() method returns a FetchedTranscript object that is iterable
                segment_count = len(fetched_transcript)
                print(f'Successfully fetched {segment_count} segments')

                # Format captions - iterate over the FetchedTranscript
                captions = []
                for snippet in fetched_transcript:
                    captions.append({
                        'start': snippet.start,
                        'duration': snippet.duration,
                        'text': snippet.text.strip()
                    })

                self.send_json_response(200, {
                    'success': True,
                    'hasCaptions': True,
                    'language': 'en',
                    'isAutoGenerated': True,
                    'captions': captions,
                    'trackInfo': {
                        'language': 'English',
                        'isAutoGenerated': True
                    }
                })

            except Exception as e:
                print(f'Error: {str(e)}')
                self.send_json_response(500, {
                    'error': 'Internal server error',
                    'message': str(e)
                })
        else:
            self.send_error(404)

    def do_GET(self):
        if self.path == '/test-captions.html':
            # Serve the test page
            try:
                file_path = os.path.join('app', 'test-captions.html')
                with open(file_path, 'rb') as f:
                    self.send_response(200)
                    self.send_header('Content-type', 'text/html')
                    self.end_headers()
                    self.wfile.write(f.read())
            except FileNotFoundError:
                self.send_error(404, 'File not found')
        else:
            self.send_error(404)

    def send_json_response(self, status_code, data):
        self.send_response(status_code)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(json.dumps(data).encode('utf-8'))

def run(port=8000):
    server_address = ('', port)
    httpd = HTTPServer(server_address, CaptionHandler)
    print(f'Starting caption server on port {port}...')
    print(f'Test page: http://localhost:{port}/test-captions.html')
    print('Press Ctrl+C to stop')
    httpd.serve_forever()

if __name__ == '__main__':
    # Use PORT environment variable if available (for Railway/Heroku/etc)
    port = int(os.environ.get('PORT', 8000))
    run(port)
